services:
  kube-runner:
    build: .
    security_opt:
      - apparmor:unconfined
      - seccomp=unconfined
    env_file: .env
    environment:
      - REGISTRY=harbor.ryzen.me
      - REGISTRY_USERNAME=ryzen
      - BUILDKITD_FLAGS=--oci-worker-no-process-sandbox
      - LEVEL=20 #10 = debug, 20 = info, 30 = warning, 40 = error
    volumes:
      - "./config.yml:/app/config.yml"