services:
  kube-runner:
    build: .
    security_opt:
      - apparmor:unconfined
      - seccomp=unconfined
    env_file: .env
    environment:
      - REGISTRY=harbor.ryzen.me
      - REGISTRY_USERNAME=ryzen
      - BUILDKITD_FLAGS=--oci-worker-no-process-sandbox
    volumes:
      - "./config.yaml:/app/config.yaml"