services:
  kube-runner:
    build: .
    # cap_add:
    #   - CAP_SYS_ADMIN
    #   - MKNOD
    # devices:
    #   - /dev/fuse
    # security_opt:
    #   - label=disable
    privileged: true
    env_file: .env
    environment:
      - WERF_BUILDAH_MODE=auto
    volumes:
      - "./config.yaml:/app/config.yaml"